name: Eslint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.8.0
      - name: Eslint
        run: |
          yarn install
          yarn lint
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Lint